version: '3.8'

services:
  app:
    image: ghcr.io/${REPO_NAME}/${IMAGE_NAME}:latest
    restart: unless-stopped
    environment:
      HOSTNAME: "${HOSTNAME}"
      AUTH_URL: ${HOSTNAME}
      DATABASE_URL: "/app/database/database.sqlite"
      SENTRY_AUTH_TOKEN: "${SENTRY_AUTH_TOKEN}"
      NEXT_PUBLIC_SENTRY_DSN: "${NEXT_PUBLIC_SENTRY_DSN}"
      SENTRY_ORG: "${SENTRY_ORG}"
      SENTRY_PROJECT: "${SENTRY_PROJECT}"
      AUTH_SECRET: "${AUTH_SECRET}"
      AUTH_GITHUB_ID: "${AUTH_GITHUB_ID}"
      AUTH_GITHUB_SECRET: "${AUTH_GITHUB_SECRET}"
      AUTH_TRUST_HOST: "true"
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - sqlite-data:/app/database

volumes:
  sqlite-data:


