version: '3.8'

services:
  app:
    image: ghcr.io/${REPO_NAME}/${IMAGE_NAME}:latest
    environment:
      DATABASE_URL: "sqlite:/app/database/database.sqlite"
      CLERK_SECRET_KEY: "${CLERK_SECRET_KEY}"
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: "${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}"
      SENTRY_AUTH_TOKEN: "${SENTRY_AUTH_TOKEN}"
      NEXT_PUBLIC_SENTRY_DSN: "${NEXT_PUBLIC_SENTRY_DSN}"
      SENTRY_ORG: "${SENTRY_ORG}"
      SENTRY_PROJECT: "${SENTRY_PROJECT}"
    volumes:
      - sqlite-data:/app/database

volumes:
  sqlite-data:
