version: '3.8'

services:
  app:
    image: ghcr.io/${REPO_NAME}/${IMAGE_NAME}:latest
    restart: unless-stopped
    environment:
      DATABASE_URL: "/app/database/database.sqlite"
      SENTRY_AUTH_TOKEN: "${SENTRY_AUTH_TOKEN}"
      NEXT_PUBLIC_SENTRY_DSN: "${NEXT_PUBLIC_SENTRY_DSN}"
      SENTRY_ORG: "${SENTRY_ORG}"
      SENTRY_PROJECT: "${SENTRY_PROJECT}"
      AUTH_SECRET: "${AUTH_SECRET}"
      AUTH_GITHUB_ID: "${AUTH_GITHUB_ID}"
      AUTH_GITHUB_SECRET: "${AUTH_GITHUB_SECRET}"

    volumes:
      - sqlite-data:/app/database

volumes:
  sqlite-data:
