version: '3.8'

services:
  app:
    image: ghcr.io/${REPO_NAME}/${IMAGE_NAME}:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NEXT_PUBLIC_ROOT_PATH=${NEXT_PUBLIC_ROOT_PATH:?Please set NEXT_PUBLIC_ROOT_PATH in .env}
      - DATABASE_URL=${DATABASE_URL:?Please set DATABASE_URL in .env}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY:?Please set CLERK_SECRET_KEY in .env}
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY:?Please set NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY in .env}
      - SENTRY_AUTH_TOKEN=${SENTRY_AUTH_TOKEN:?Please set SENTRY_AUTH_TOKEN in .env}
      - NEXT_PUBLIC_SENTRY_DSN=${NEXT_PUBLIC_SENTRY_DSN:?Please set NEXT_PUBLIC_SENTRY_DSN in .env}
      - SENTRY_ORG=${SENTRY_ORG:?Please set SENTRY_ORG in .env}
      - SENTRY_PROJECT=${SENTRY_PROJECT:?Please set SENTRY_PROJECT in .env}
    volumes:
      - sqlite-data:/app/database

volumes:
  sqlite-data:
